language: objective-c
osx_image: xcode8
before_script:
    - bundle install
script:
    - xcodebuild -project SuperDelegate.xcodeproj -scheme SuperDelegate -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE" test
    - xcodebuild -project Sample/SampleDelegate/SampleDelegate.xcodeproj -scheme SampleDelegate -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE" build
    - pod lib lint --verbose --fail-fast
