language: objective-c
osx_image: xcode7.3
before_script:
    - bundle install
script:
    - xctool -project SuperDelegate.xcodeproj -scheme SuperDelegate -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPad Air 2" test
    - xcodebuild -project Sample/SampleDelegate/SampleDelegate.xcodeproj -scheme "SuperDelegate" -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 build
    - pod lib lint --verbose --fail-fast
